server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: backend-chek-media
  datasource:
    url: ${DB_URL:jdbc:h2:mem:chek_media;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
    username: ${DB_UID:sa}
    password: ${DB_PWD:}
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:15}

springdoc:
  api-docs:
    path: /openapi.json

